# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: hfwd
    goos:
     - windows
     - darwin
     - linux
     - freebsd
    goarch:
     - 386
     - amd64
archive:
  format: binary
  replacements:
    386: 386
    amd64: 64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
    - '^Merge pull request #\d+ from'
    - '^Merge remote-tracking branch'
